'''__init__.py: Initializes astro_data_tools package.

The astro_data_tools package contains code for organizing, manipulating, and
plotting data generated by astrophysical magnetohydrodynamics (MHD) simulations,
and is specifically designed for use with the Athena++ library. More information
on Athena++ can be found in the athena.py module.

Example import statement:
import astro_data_tools as adt
import astro_data_tools.athena
import astro_data_tools.plotting
-> The modules can now be accessed as adt.athena, adt.plotting.

"from astro_data_tools import *" will import athena and plotting modules.
'''

__author__ = "Mark Abate"
__date__ = "May 8, 2021"

# Automatically imports generic.py
from generic import *

__all__ = ['athena', 'plotting']
